name: mini_todo
description: A compact todo app
publish_to: 'none'
version: 0.2.0+4

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_bloc: ^8.0.1
  drift: ^1.5.0
  sqlite3_flutter_libs: ^0.5.5
  path_provider: ^2.0.9
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  drift_dev: ^1.5.2
  build_runner: ^2.1.10
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/app-icon/icon.png

flutter_intl:
  enabled: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app-icon/icon.png"
  adaptive_icon_background: "#fafafa"
  adaptive_icon_foreground: "assets/app-icon/icon-foreground.png"